name: Rust

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    # Use MSRV for the build job
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.56
        default: true
        profile: minimal
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
    # Use stable for other jobs
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        default: true
        profile: minimal
        components: rustfmt, clippy
    - name: Run tests
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --all
    - name: Check formatting
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --all --check
    - name: Catch common mistakes
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: --all-targets --workspace -- -D warnings
    - name: Regenerate Unicode tables
      run: mv src/tables.rs tables.rs.bak && cd tables && cargo run && cd .. && diff src/tables.rs tables.rs.bak
